Tests oas
Laboratoria/impl-data-lovers pull request #8
Opened 2023-08-04 21:29 UTC by DeysiVergara

2023-08-07 17:51 UTC, unjust requested changes

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +    it('Se usan atributos de modelo de caja en clase CSS para <ul>', () => {
dudo si deberiamos chequear el `ul` para rules de `box-model` para mi tiene mas sentido en los `lis`

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +      let allRulesAttributes = [];
Ahora estas chequando todos los classes que aplican a todos los lis y concatenando todos sus rules, para ver si usan box model attreibutos en algun momento.
Tiene mas sentido para mi ver el class que usan con  `li` (`.card`) y quiza un hijo que podemos definir como un `div` que contiene un class tipo `.info`. Y chequar los rules y attributos de solo esos clases.

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +import { renderView } from '../../src/data.js';
`import` puede ser antes?

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
no creo los tests de class y name en header seria necesario.

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
>      const h1 = header.querySelector('h1');
mueve eso dentro el test particular si no usamos en mas que un test

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
>      it('<h1> no tiene atributo "name"', () => {
no creo es necesario el name test para h1

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +    it('<header> es padre de un <h2>', () => {
porque? creo h2 no pertenece en un header. si hay h2 en la pagina, seria afuera en el main

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +        expect(previousFor).toBe(element.id);
👍

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +    Array.from(select).forEach((element) => {
hmm yo creo mejor poner el forEach dentro cada test

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +    const uls = lis.querySelectorAll('ul');
lis son dentro de uls

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +
seria bueno probar que los selects son dentro de un bar con flexbox aplicado.
y si podemos probar flex en el container con row y quiza flex con columna en los cards?

2023-08-07 17:51 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +      let allRulesAttributes = [];
Tambien si vamos a necesitar la misma logica para sacar los rules por classes podemos definir un function reusable como `getAttributesForClasses` o algo

2023-08-07 22:44 UTC, DeysiVergara commented on src/style.css
> +    padding: auto;
Lo modifique por un margin, lo coloque probando el test y se me paso cambiarlo.

2023-08-07 23:26 UTC, unjust reviewed
Gracias Deysi! Buscamos un espacio mañana para pensar juntas en alguno puntos.

2023-08-07 23:26 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +    it('li elementos tienen class .card', () => {
mejor explicado :)
y aun tenemos que pensar en este test mejor, porque con eso, probamos que `.card` existe con reglas en el CSS, y este selector esta usado en el document, pero nada relaciona este class con un `li` en si. quiza mejor hablamos.
moveria lineas [46 y 47 dentro si](https://github.com/Laboratoria/DEV-999-data-lovers/pull/8/commits/f254bcfcc7087ea6cd3a5354e1124c1e305b29a7#diff-9004701ccaf264976870c1b8be66d2ef2835ffa3b28a2c259abcf242bcdf3120R46-R47)? o necesitamos estes variables por otros tests?

2023-08-07 23:26 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +      let allRulesAttributes = [];
movemos linea 48 y 49 aqui si no estan usados en otro tests.

2023-08-11 17:06 UTC, unjust commented on README.md
> +  [`selector del DOM getElementById`](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById).
no se si necesitamos agregar eso, pero podemos discutirlo.

2023-08-11 17:07 UTC, unjust commented on README.md
> +    - [ ] La aplicación NO declara variables con  `var`.
aqui preguntaria si esos agregamos o dejamos al linter.

2023-08-11 17:08 UTC, unjust commented on README.md
> +    para evaluar condiciones.
hm no se. a ver si siempre es necesario. tambien pieso en ternario... pero no se si siempre seria necesario tampoco.

2023-08-11 17:09 UTC, unjust commented on README.md
> +    - [ ] En el archivo data.js contiene el método reduce para obtener estadisticas.
no se si eso es en la parte de funciones o "arrays"

2023-08-11 17:11 UTC, unjust commented on README.md
> +  - [ ]<ul> o <ol> para lista de los items.
agregaria aqui los itemprops o dl/dt

2023-08-15 17:28 UTC, unjust requested changes

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +        expect(item.getAttribute('class')).toBe('card');
creo aqui este es mas probando que los elementos de html tiene un attributo y quiza va en html tests.
Probamos aqui si usan un selector se llama `.card` en el css
o quiza que hay un selector en el css que coinciden con uno de los classes que vemos en los elementos `li`

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +      });
Prueba si esta funciona
```suggestion
      const allRulesAttributes = ulClasses.reduce((allRules, ulClass) => {
        const rules = getRulesForSelector(`.${ulClass}`);
        const ulRulesAttributes = rules[0].declarations.map((declaration) => declaration.property);
        return [...allRules, ulRulesAttributes];
      }, []);
```

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +      const selectRules = getRulesForSelector(`[name=${name}]`);
ahora que pienso, porque los `selects` si necesitan un `id`, podemos relajar esta regla y decir un selector de `class` porque deberia tener al menos 2 selects en el UI con el mismo presentacion.
Pienso que en el `javascript` pedimos que no usan `getElementById` o al menos un `querySelector` para los selects

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +        allRulesAttributes = allRulesAttributes.concat(ulRulesAttributes);
este es el mismo de linea 63. Yo separaria esta funcion arriba para ser reutilizable.

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +    it('<Hay un h2 en el main> es padre de un <h2>', () => {
`<main> contiene un elemento <h2>` quiza seria mejor.

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +    const h2 = main.querySelector('h2');
```suggestion
     const h2  = document.querySelector('main h2');
```

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +    it('La aplicación usa un <li>', () => {
"La aplicacion usa un `<ul>` con `<li>` para los elementos de data"
`document.querySelector('#root ul > li');`

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +    it('<footer> es padre de un <p>', () => {
no me parece necesario este test. quiza que hay un footer que tiene contenido

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-javascript.spec.js
> +  it('Se usan métodos para manipular arrays como "filter"', () => {
no se si podemos ser mas exacta como - "se usan metodos filter en su funcion `filterData`"

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-web-api.spec.js
> +    // para probar que hay algun lugar donde se use e.target, como aqui: const arrayType = filterData(data.pokemon, 'type', e.target.value);
quiero ver si esta test tambien pasa si hay
```
const value = e.target.value;
const propertyName = e.target.name;
filterData(data.pokemon, propertyName, value);
```

2023-08-15 17:28 UTC, unjust commented on tests-read-only/oa/oa-web-api.spec.js
> +  });
aun estoy pensando que podemos ser flexible entre innerHTML y createElement, pero no exigir los dos.

2023-08-15 17:52 UTC, DeysiVergara commented on tests-read-only/oa/oa-css.spec.js
> +      const selectRules = getRulesForSelector(`[name=${name}]`);
Vamos por el selector de etiqueta.

2023-08-15 17:54 UTC, DeysiVergara commented on tests-read-only/oa/oa-css.spec.js
> +    it('Se usan atributos de modelo de caja en clase CSS para <ul>', () => {
Voy a chequear, quizás borrar y probarlos en los lis

2023-08-15 18:03 UTC, DeysiVergara commented on tests-read-only/oa/oa-css.spec.js
> +
Probar que tenga display flex, en el padre de los controles.

2023-08-15 18:05 UTC, DeysiVergara commented on tests-read-only/oa/oa-html.spec.js
Solo probar que hay un header, eliminamos la prueba del name.

2023-08-15 18:10 UTC, DeysiVergara commented on tests-read-only/oa/oa-html.spec.js
> +    it('<footer> es padre de un <p>', () => {
solo que exista y que tenga contenido.

2023-08-15 18:21 UTC, DeysiVergara commented on tests-read-only/oa/oa-javascript.spec.js
> +  it('Se usan métodos para manipular arrays como "filter"', () => {
Revisar que las funciones contengan los métodos de array.

2023-08-15 22:38 UTC, DeysiVergara commented on tests-read-only/oa/oa-css.spec.js
> +      });
Funciona, cambie la ultima parte y use un concat igual, para evitar el array de arrays que salia.

2023-08-16 19:41 UTC, unjust commented on README.md
>  Los criterios para considerar que has completado este proyecto son:
puedes hacer un checkout del README de implementacion para no tener problemas de conflicto?

2023-08-16 20:00 UTC, unjust requested changes
Hay que resolver los conflictos primero, actualizar con `implementacion`

2023-08-16 21:10 UTC, DeysiVergara commented on tests-read-only/oa/oa-css.spec.js
> +      const selects = parentContainer.querySelectorAll('select')
Me complico viendo que es mas sencillo buscar alguna clase que tenga un nombre definido, que definir la estructura, porque en mi caso es el padre del padre, por eso me fui por la clase.

2023-08-17 18:02 UTC, unjust commented on tests-read-only/oa/oa-css.spec.js
> +      const selects = parentContainer.querySelectorAll('select')
voy a anotarlo para nuevo issue #15

2023-08-17 18:03 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
>        expect(header.getAttribute('class')).toBeNull();
voy a anotarlo en nuevo issue #15

2023-08-17 18:04 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
>      it('<h1> no tiene atributo "class"', () => {
igual en #15

2023-08-17 18:07 UTC, unjust commented on tests-read-only/oa/oa-html.spec.js
> +      })
puedo imaginar que ellas usan un class pero vamos a ver en la prueba

2023-08-17 18:10 UTC, unjust reviewed
Algunas cosas puse en un nuevo issue #15 pero hay algunos comentarios que queda pendiente

2023-08-17 18:10 UTC, unjust commented on tests-read-only/oa/oa-javascript.spec.js
> +  });
@DeysiVergara creo eso seria problematico por se caso solo uso un bucle.

2023-08-17 18:10 UTC, unjust commented on tests-read-only/oa/oa-web-api.spec.js
> +      addEventListenerCalls.some((node) => node.arguments[1].body.body[0].declarations[0].init.arguments[2].object.property.name === 'target')
tengo dudas sobre eso. voy a marcarlo en el issue #15

2023-08-17 18:10 UTC, unjust commented on tests-read-only/oa/oa-web-api.spec.js
> +  it('Existe un createElement', () => {
existe manipulacion dinamica con createElement o templateStrings

2023-08-17 18:36 UTC, unjust approved these changes

2023-08-17 18:36 UTC, merged